version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: Connecting-Minds
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init/index.js:/docker-entrypoint-initdb.d/init-mongo-db-with-collections.js:ro
    networks:
      - mongodb_network

networks:
  mongodb_network:

volumes:
  mongodb_data:
    driver: local